name: build
on:
  push:
    paths:
      - '*/**'
    branches:
      - main

jobs:
  build:
    name: Build Flask application
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/flask-app:latest --label "runnumber=${GITHUB_RUN_ID}"
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push image
        run: docker push ghcr.io/${{ github.repository_owner }}/flask-app:latest
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'PROD'
    steps:
      - name: Setup SSH
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.PRIVATE_KEY }}")
          ssh deploy@52.224.246.238 'export GHCR_USERNAME=${{ github.repository_owner }} GHCR_TOKEN=${{ secrets.GITHUB_TOKEN }}; bash -s' < deploy-container.sh
      - name: Check Deployment Status
        run: |
          if [ $? -ne 0 ]; then
            echo "Deployment failed"
            exit 1
          fi
