name: build
on:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - main

jobs:
  build:
    name: Build Flask application
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/flask-app:latest --label "runnumber=${GITHUB_RUN_ID}"
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push image
        run: docker push ghcr.io/${{ github.repository_owner }}/flask-app:latest
