name: deploy
on:
  push:
    paths:
      - '*/**'
    branches:
      - main

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    # needs: build
    environment:
      name: 'PROD'
    steps:
      - name: Setup SSH
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.PRIVATE_KEY }}")
          ssh-keyscan 52.224.246.238 >> ~/.ssh/known_hosts
          ls -la && pwd
          ssh deploy@52.224.246.238
      # - name: Check Deployment Status
      #   run: |
      #     if [ $? -ne 0 ]; then
      #       echo "Deployment failed"
      #       exit 1
      #     fi
