name: deploy
on:
  workflow_run:
    workflows:
      - build
    types:
      - completed

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'PROD'
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.PRIVATE_KEY }}")
          mkdir -p /home/runner/.ssh && chmod 700 ~/.ssh
          ssh-keyscan ${{ vars.HOST_ADDRESS }} >> ~/.ssh/known_hosts
          ssh ${{ vars.USER }}@${{ vars.HOST_ADDRESS }} 'export GHCR_USERNAME=${{ github.repository_owner }} GHCR_TOKEN=${{ secrets.GITHUB_TOKEN }}; bash -s' < deploy-container.sh
        working-directory: scripts/
      - name: Check Deployment Status
        run: |
          if [ $? -ne 0 ]; then
            echo "Deployment failed"
            exit 1
          fi
