name: build
on:
  push:
    paths:
      - '*/**'
    branches:
      - main

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    # needs: build
    environment:
      name: 'PROD'
    steps:
      - name: Setup SSH
        working-directory: scripts/
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.PRIVATE_KEY }}")
          ls -la && pwd
          ssh deploy@52.224.246.238 'export GHCR_USERNAME=${{ github.repository_owner }} GHCR_TOKEN=${{ secrets.GITHUB_TOKEN }}; bash -s' < deploy-container.sh
      - name: Check Deployment Status
        run: |
          if [ $? -ne 0 ]; then
            echo "Deployment failed"
            exit 1
          fi
